/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    cats: Cat;
    media: Media;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  roles?: ('admin' | 'gestor' | 'user')[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cats".
 */
export interface Cat {
  id: string;
  image: string | Media;
  name: string;
  birthDate: string;
  location?:
    | (
        | 'Alava'
        | 'Albacete'
        | 'Alicante'
        | 'Almería'
        | 'Asturias'
        | 'Avila'
        | 'Badajoz'
        | 'Barcelona'
        | 'Burgos'
        | 'Cáceres'
        | 'Cádiz'
        | 'Cantabria'
        | 'Castellón'
        | 'Ciudad Real'
        | 'Córdoba'
        | 'La Coruña'
        | 'Cuenca'
        | 'Gerona'
        | 'Granada'
        | 'Guadalajara'
        | 'Guipúzcoa'
        | 'Huelva'
        | 'Huesca'
        | 'Islas Baleares'
        | 'Jaén'
        | 'León'
        | 'Lérida'
        | 'Lugo'
        | 'Madrid'
        | 'Málaga'
        | 'Murcia'
        | 'Navarra'
        | 'Orense'
        | 'Palencia'
        | 'Las Palmas'
        | 'Pontevedra'
        | 'La Rioja'
        | 'Salamanca'
        | 'Segovia'
        | 'Sevilla'
        | 'Soria'
        | 'Tarragona'
        | 'Santa Cruz de Tenerife'
        | 'Teruel'
        | 'Toledo'
        | 'Valencia'
        | 'Valladolid'
        | 'Vizcaya'
        | 'Zamora'
        | 'Zaragoza'
      )
    | null;
  sex?: ('macho' | 'hembra') | null;
  bodydescription?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  health?: {
    revisions?: {
      vaccinated?: boolean | null;
      sterilized?: boolean | null;
      dewormed?: boolean | null;
    };
    weight?: number | null;
    notes?:
      | {
          [k: string]: unknown;
        }[]
      | null;
  };
  availability?: ('disponible' | 'no disponible') | null;
  characteristics?: {
    personality?:
      | ('tranquilo' | 'jugueton' | 'carinoso' | 'amigable' | 'timido' | 'miedoso' | 'independiente')[]
      | null;
    compatibility?: ('compatible' | 'incompatible') | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: string | Media | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    default?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}